[package]
name = "danae/practice-game"
version = "0.1.0"
registry = "https://github.com/UpliftGames/wally-index"
realm = "shared"

[dependencies]
testez = "roblox/testez@0.4.1"
knit = "sleitnick/knit@1.7.0"

# Utils
TableUtil = "sleitnick/table-util@1.2.0"
Input = "sleitnick/input@2.1.1"
Timer = "sleitnick/timer@1.1.2"
Maid = "flamenco687/maid@3.2.2"
Signal = "sleitnick/signal@1.2.1"
Silo = "sleitnick/silo@0.1.1"
Cmdr = "evaera/cmdr@1.12.0"